### Get Token from Keycloak (Front would do this and send the token to Back)
# IMPORTANT: Set KEYCLOAK_CLIENT_SECRET in the .env file!
# @name tokenrequest
POST /realms/master/protocol/openid-connect/token HTTP/1.1
Host: localhost:8080
Content-Type: application/x-www-form-urlencoded

&grant_type=password
&client_id=admin-cli
&username=djangoadmin@example.com
&password=admin
&client_secret={{$dotenv KEYCLOAK_CLIENT_SECRET}}


###
@token = {{tokenrequest.response.body.access_token}}


### Hello <request.user>
GET /api/hello/ HTTP/1.1
Host: localhost:8000
Authorization: Bearer {{token}}


### Register a new user
POST /api/register_user/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{ "email": "test@example.com", "password": "test" }


### Set user field(s)
POST /api/set_user_field/ HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{ "email": "test@example.com", "field": "preferred_color_scheme", "value": "dark" }
